name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 124.223.1.32
          username: ubuntu
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GITHUB_TOKEN
          script: |
            cd /home/ubuntu/Backend-server-Veda
            git pull https://peterxie990624:${{ secrets.GH_TOKEN }}@github.com/peterxie990624/Backend-server-Veda.git main
            npm install
            pm2 restart server || node server.js &
